$(document).ready(function(){
    $(".menu-item").each(function(){
        $(this).hover(function(){
            $(".pop_menu").fadeIn();
        },function(){
            $(".pop_menu").fadeOut();
        })
    })
})
