$(document).ready(function(){
    $(".menu_item").each(function(){
        $(this).hover(function(){
            $(this)
                .find(".pop_menu")
                .addClass("mouse-in")
                .stop().fadeIn();
        },function(){
            $(this)
                .find(".pop_menu")
                .removeClass("mouse-in")
                .stop()
                .fadeOut();
        });
    });
});
